const coreIdeas = [
 {id:1,name:'TideTurn',category:'Climate',icon:'◒',color:'cyan',tag:'Circular economy',score:94,desc:'A local operating system that turns commercial food waste into verified, tradable compost credits.',problem:'Small businesses want to reduce landfill waste, but collection is fragmented and impact is difficult to prove.',solution:'TideTurn coordinates pickups, routes material to nearby processors, and gives each kilogram a traceable environmental record.',market:'$62B global organic-waste management market',stage:'Early signal',metrics:['2.4t waste diverted / partner','38% lower collection cost','12 pilot restaurants'],tags:['B2B SaaS','Climate tech','Logistics']},
 {id:2,name:'Morrow',category:'Health',icon:'✦',color:'violet',tag:'Preventive care',score:91,desc:'A quiet daily companion that helps caregivers spot cognitive decline before a crisis.',problem:'Families often notice changes in ageing relatives only after a serious incident.',solution:'With consent, Morrow turns small routine signals into weekly, human-readable wellbeing nudges for families and care teams.',market:'$47B ageing-in-place technology market',stage:'Rising',metrics:['8.2M US care households','7 day insight cycle','3 consent layers'],tags:['Health tech','Care economy','AI']},
 {id:3,name:'KiteGrid',category:'Energy',icon:'⌁',color:'lime',tag:'Microgrid intelligence',score:89,desc:'Software that lets apartment communities buy, share, and optimise rooftop solar together.',problem:'Shared buildings leave solar capacity unused because ownership and billing are hard to coordinate.',solution:'KiteGrid models demand, allocates energy fairly, and automates transparent resident billing.',market:'$31B distributed energy resource software market',stage:'Validation',metrics:['22% lower energy bill','1,600 homes modelled','4 min onboarding'],tags:['Energy','Proptech','B2B2C']},
 {id:4,name:'SkillMint',category:'Future of Work',icon:'⌘',color:'orange',tag:'Skills infrastructure',score:87,desc:'A verified project portfolio that makes practical skills portable between employers.',problem:'Resumes do not show what someone can actually do, especially for emerging roles.',solution:'SkillMint captures evidence from real projects and converts it into shareable, role-specific skill proofs.',market:'$38B talent intelligence market',stage:'Rising',metrics:['46% faster screening','19 role pathways','9 hiring partners'],tags:['HR tech','Education','Marketplace']},
 {id:5,name:'TraceThread',category:'Consumer',icon:'◉',color:'pink',tag:'Product provenance',score:84,desc:'The digital passport consumers use to see who made their clothes and where materials came from.',problem:'Ethical claims in fashion are hard for shoppers to verify at the moment of purchase.',solution:'TraceThread gives every garment a scannable story, repair guide, and resale-ready ownership record.',market:'$15B sustainable fashion services market',stage:'Early signal',metrics:['83% scan completion','14 brand interviews','2x resale intent'],tags:['Consumer','Fashion','Web3']},
 {id:6,name:'FieldNote',category:'Food',icon:'⌗',color:'yellow',tag:'Farm intelligence',score:82,desc:'A voice-first field journal that turns farmers’ observations into crop decisions.',problem:'Small farmers capture rich knowledge in notebooks, if they capture it at all.',solution:'FieldNote records observations offline and surfaces clear, local recommendations when a connection returns.',market:'$11B precision agriculture software market',stage:'Validation',metrics:['3 local languages','61% less admin time','8 farm co-ops'],tags:['Agtech','Voice','Offline-first']}
];
const getCustomIdeas = () => JSON.parse(sessionStorage.getItem('customIdeas') || '[]');
const ideas = [...getCustomIdeas(), ...coreIdeas];
const categories = ['All', ...new Set(ideas.map(idea => idea.category))];
const addIdea = ({name, category, desc}) => {
 const customIdea = {id:Date.now(),name,category,desc,icon:'✧',color:'violet',tag:'Community submission',score:72,problem:'A founder-submitted opportunity ready to be validated with real customer conversations.',solution:desc,market:'Market potential to be researched',stage:'New signal',metrics:['Community-submitted','Ready for discovery','Saved in your session'],tags:['User idea',category,'Early stage']};
 sessionStorage.setItem('customIdeas',JSON.stringify([customIdea,...getCustomIdeas()])); return customIdea;
};
const getSaved = () => JSON.parse(sessionStorage.getItem('savedIdeas') || '[]');
const isSaved = id => getSaved().includes(id);
const toggleSaved = id => { const saved=getSaved(); const next=saved.includes(id)?saved.filter(item=>item!==id):[...saved,id]; sessionStorage.setItem('savedIdeas',JSON.stringify(next)); return next.includes(id); };
